conan + cmake stuff
biocad/cuq pull request #2
Opened 2020-11-16 06:53 UTC by akhoroshev

2020-11-19 05:17 UTC, tiermak requested changes

2020-11-19 05:17 UTC, tiermak commented on .gitlab-ci.yml
> +build-memcheck-test:
Do we need it? We don't do memcheck tests anyway as they last forever :(

2020-11-19 05:17 UTC, tiermak commented on conanfile.py
> +    settings = "os", "build_type", "arch", "compiler", "CUDA"
`arch` again, do we need it?

2020-11-19 05:17 UTC, tiermak commented on conanfile.py
> +        self.cpp_info.system_libs = ["cudart", "nvidia-ml", "stdc++"]
Let's leave a comment why it's needed.

2020-11-19 14:07 UTC, akhoroshev commented on conanfile.py
> +    settings = "os", "build_type", "arch", "compiler", "CUDA"
на самом деле дефолтная настройка, пусть будет! А то как приедут к нам arm сервера...
arch: [x86, x86_64, ppc64le, ppc64, armv6, armv7, armv7hf, armv8, sparc, sparcv9, mips, mips64, avr, armv7s, armv7k]

2020-11-19 14:07 UTC, akhoroshev commented on .gitlab-ci.yml
> +build-memcheck-test:
так даже лучше!

2020-11-19 14:11 UTC, akhoroshev commented
@tiermak апрувни но не мердж

2020-11-20 10:44 UTC, tiermak approved these changes

2020-11-20 11:17 UTC, merged